// Download the web fonts the interface uses into public/fonts/ so page loads
// never contact Google. Run `npm run fonts:fetch` after changing the glyph list
// in src/ui/materialSymbolsGlyphs.json, then commit the regenerated files.
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../', import.meta.url));
const FONTS_DIR = path.join(REPO_ROOT, 'public/fonts');
const GLYPHS_FILE = path.join(REPO_ROOT, 'src/ui/materialSymbolsGlyphs.json');

/** Where public/fonts/ is served from. */
const FONTS_URL_PATH = '/fonts';
const STYLESHEET_NAME = 'fonts.css';
const LICENSES_DIR_NAME = 'licenses';
/** Unicode subsets worth shipping; Cyrillic, Greek and Vietnamese are dropped. */
const KEPT_SUBSETS = new Set(['latin', 'latin-ext']);
/** The generated stylesheet records the glyphs it was built from on this line. */
export const ICON_NAMES_MARKER = 'material-symbols icon_names:';

const CSS2_API = 'https://fonts.googleapis.com/css2';
const TEXT_FAMILIES =
  'family=JetBrains+Mono:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600&display=swap';
// `display=block` keeps a ligature icon invisible until the font loads, instead
// of flashing its literal name (e.g. `right_panel_open`) in a fallback font.
const ICON_FAMILY =
  'family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,400,0,0&display=block';
/** Google emits only the prefixed ligature switch; this standard one follows it. */
const STANDARD_LIGATURES = "font-feature-settings: 'liga';";
// The CSS2 API only answers with woff2 sources for user agents it knows support it.
const WOFF2_USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';
const LICENSES = [
  {
    file: 'Inter-OFL.txt',
    url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/inter/OFL.txt',
  },
  {
    file: 'JetBrainsMono-OFL.txt',
    url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/jetbrainsmono/OFL.txt',
  },
  {
    file: 'MaterialSymbols-Apache-2.0.txt',
    url: 'https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE',
  },
];

/** A Google CSS2 `@font-face` rule with the subset comment that precedes it. */
const FONT_FACE_RULE =
  /(?:\/\*\s*([a-z-]+)\s*\*\/\s*)?@font-face\s*\{[^}]*\}\s*/g;

function fileSlug(family) {
  return family.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-');
}

/**
 * Drop unwanted subsets from Google CSS2 output and point every remaining
 * `@font-face` at a local file. Rules that are not `@font-face` (the
 * `.material-symbols-outlined` ligature class) pass through unchanged.
 * @returns {{ css: string, downloads: Map<string, string> }} the rewritten
 *   stylesheet and remote URL -> local file name.
 */
export function localizeFontFaces(css, downloads = new Map()) {
  const localized = css.replace(FONT_FACE_RULE, (rule, subset) => {
    if (subset && !KEPT_SUBSETS.has(subset)) return '';
    const family = /font-family:\s*'([^']+)'/.exec(rule)?.[1];
    const source = /src:\s*url\(([^)]+)\)\s*format\('woff2'\)/.exec(rule)?.[1];
    if (!family || !source) {
      throw new Error(`Expected a woff2 @font-face rule, received: ${rule}`);
    }
    if (!downloads.has(source)) {
      const base = [fileSlug(family), subset].filter(Boolean).join('-');
      const taken = new Set(downloads.values());
      const weight = /font-weight:\s*(\d+)/.exec(rule)?.[1];
      const file = taken.has(`${base}.woff2`)
        ? `${base}-${weight}.woff2`
        : `${base}.woff2`;
      downloads.set(source, file);
    }
    return rule.replace(source, `${FONTS_URL_PATH}/${downloads.get(source)}`);
  });
  return { css: localized, downloads };
}

/**
 * Pair each prefixed `-webkit-font-feature-settings: 'liga'` with the standard
 * property, so icon ligatures do not depend on a vendor-prefixed declaration.
 */
export function withStandardLigatures(css) {
  return css.replace(
    /^([ \t]*)-webkit-font-feature-settings: 'liga';\n/gm,
    (line, indent) => `${line}${indent}${STANDARD_LIGATURES}\n`,
  );
}

/** The generated stylesheet's banner, which records the glyph subset. */
export function stylesheetHeader(iconNames) {
  return [
    '/* Generated by scripts/fetch-fonts.mjs (npm run fonts:fetch). Do not edit.',
    ` * Inter, JetBrains Mono: SIL Open Font License 1.1; see ${LICENSES_DIR_NAME}/.`,
    ` * Material Symbols Outlined: Apache License 2.0; see ${LICENSES_DIR_NAME}/.`,
    ` * ${ICON_NAMES_MARKER} ${iconNames.join(',')}`,
    ' */',
    '',
  ].join('\n');
}

async function fetchOk(url, init) {
  const response = await fetch(url, init);
  if (!response.ok) throw new Error(`${response.status} fetching ${url}`);
  return response;
}

async function fetchStylesheet(query) {
  const response = await fetchOk(`${CSS2_API}?${query}`, {
    headers: { 'User-Agent': WOFF2_USER_AGENT },
  });
  return response.text();
}

/** Download every font and license into memory, keyed by its output path. */
async function downloadFiles(downloads) {
  const fonts = await Promise.all(
    [...downloads].map(async ([url, file]) => [
      file,
      Buffer.from(await (await fetchOk(url)).arrayBuffer()),
    ]),
  );
  const licenses = await Promise.all(
    LICENSES.map(async ({ file, url }) => [
      path.join(LICENSES_DIR_NAME, file),
      await (await fetchOk(url)).text(),
    ]),
  );
  return [...fonts, ...licenses];
}

async function main() {
  // The CSS2 API rejects an icon_names list that is not sorted.
  const iconNames = [
    ...new Set(JSON.parse(await readFile(GLYPHS_FILE, 'utf8'))),
  ].sort();
  const downloads = new Map();
  const text = localizeFontFaces(
    await fetchStylesheet(TEXT_FAMILIES),
    downloads,
  );
  const icons = localizeFontFaces(
    await fetchStylesheet(`${ICON_FAMILY}&icon_names=${iconNames.join(',')}`),
    downloads,
  );
  // Fetch everything before touching public/fonts/, so a network failure
  // leaves the committed fonts in place rather than a half-written directory.
  const files = await downloadFiles(downloads);

  await rm(FONTS_DIR, { recursive: true, force: true });
  await mkdir(path.join(FONTS_DIR, LICENSES_DIR_NAME), { recursive: true });
  for (const [file, body] of files) {
    await writeFile(path.join(FONTS_DIR, file), body);
  }
  await writeFile(
    path.join(FONTS_DIR, STYLESHEET_NAME),
    `${stylesheetHeader(iconNames)}\n${text.css.trim()}\n\n${withStandardLigatures(icons.css).trim()}\n`,
  );
  console.log(
    `Wrote ${downloads.size} fonts and ${STYLESHEET_NAME} to ${path.relative(REPO_ROOT, FONTS_DIR)}/`,
  );
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
